metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.10.69.20, mac: '54:bf:64:5e:0b:d8', disk: sda, network_interface: enp0s31f6}
    workers:
      hosts:
        metal1: {ansible_host: 10.10.69.28, mac: '74:d0:2b:28:a5:a8', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 10.10.69.22, mac: '68:1c:a2:13:5d:24', disk: sda, network_interface: enp2s0}
